### PR TITLE
added advanced google web login page

### PR DESCRIPTION
**Pull request by usama7628674**
This is the advanced page that accepts email and password individually just like original google login page.

### CODE REVIEW

**Comment by alexmozzhakov** [comment]
So is it standard or advanced? 🤔 Animations doesn't seem to work, /accounts.login.php shouldn't be there at all. The progress bar isn't working too, but it's div is in place and visible for some reason (4 px high, but well). IMO it's worse then regular, because it doesn't seem to be programmed well. I can give it a shot sometime or you can try fixing those yourself, but meanwhile I don't merge it 😕

**Comment by usama7628674** [comment]
@alexmozzhakov What div and progess bar are you talking about?Accounts.login.php is the page that shows password field so it should be there.There are no animations.

**Comment by alexmozzhakov** [comment]
@usama7628674 `<div class="RZBuIb c8DD0"` is a progress bar. Instead of smooth (ajax?) animation we get a usual ~slow~  request to accounts.login.php

**Comment by usama7628674** [comment]
@alexmozzhakov But how am I gonna fix it?

**Pull request closed without merging**
