### PR TITLE
fix forum not redirecting to login.php in snapchat

### PR DESCRIPTION
**Pull request by usama7628674**

### CODE REVIEW

**Comment by alexmozzhakov** [comment]
That's why I've asked for a review in #51

**Comment by usama7628674** [comment]
@alexmozzhakov There was not a problen in #51 .Footer column dropdown wasn't working so I added main.js which broke forum redirection so to fix it I had to modify the file and made this PR.

**Comment by alexmozzhakov** [comment]
@usama7628674 I know, but if you were to notice footer issue in my PR there would've been no issues. Also, you could assign me to review #52 
P.S I thought `dropdown.js` is responsible for dropdown and I also broke the form while added `main.js`, so I've decided to remove it completely.

**Comment by usama7628674** [comment]
@alexmozzhakov There was an action url in main.js which was redirecting to url and and onclickbutton which was preventing Sign In button from clicking so I fixed the link and removed onclickbutton and it started working with dropdown.

**Comment by alexmozzhakov** [comment]
@usama7628674 w8, but sign in isn't redirected but returns 404. Also, I was talking about PR's and commits, not the actual code.

**Comment by usama7628674** [comment]
@alexmozzhakov It's working no 404 for me tested in firefox-esr and chrome android.

**Pull request merged**
