### PR TITLE
ported socialfishtermux to python 3

### PR DESCRIPTION
**Pull request by usama7628674**

### CODE REVIEW

**Comment by alexmozzhakov** [comment]
@usama7628674 Ok, it was somewhat messy. Except for PR you've done some related commits right away. Also, you could do a soft `git reset` in order to "squash" commits

**Comment by usama7628674** [comment]
@alexmozzhakov Messy about what?Is it not working for you?

**Comment by alexmozzhakov** [comment]
@usama7628674 I couldn't fix the code, I just can't agree with your position about unimportance of managing git neatly.
Commits titles are important in order to analyze changes done in code for example if it breaks and should be consistent throughout the project. Ex. https://github.com/An0nUD4Y/SocialFish/pull/48/commits/1132ad7eab68684e23907510715bc356c146a712 is removing unimportant `sudo` and not porting to python 3 => unrelated to the PR, https://github.com/An0nUD4Y/SocialFish/pull/48/commits/172ed3496e5f3aab0142a86b200ea6c6b4029ffb is fixing formatting https://github.com/An0nUD4Y/SocialFish/pull/48/commits/71b4e97efdeef18873f6481ee254e614b456fa0f is actually porting.  https://github.com/An0nUD4Y/SocialFish/commit/9fccc19867db0e721f0c71ad535f7d1f57db28ec should also be related to the PR IMHO. Also, first time I saw it I was like "ok, what about non-termux version". Only looking at the code helped me realize you've ported both, because "Update SocialFish.py" isn't very descriptive. I hope you got my point.

**Comment by usama7628674** [comment]
@alexmozzhakov I did notice it when I was porting but I thought it was okay so should I revert this PR?

**Comment by usama7628674** [comment]
@alexmozzhakov Fiexed it.

**Comment by alexmozzhakov** [comment]
@usama7628674 nice, this is better. 👍

**Comment by usama7628674** [comment]
@alexmozzhakov Thank you for letting me know about those commits.

**Pull request merged**
