### PR TITLE
Added the victim's outer network IP to locate the latitude and longitude functions

### PR DESCRIPTION
**Pull request by Micrafast**
After I sent the issue that was unable to get the right victim's outer network IP, the developer added a ip.php to get the victim's IP correctly, but no location, so I added the IP positioning function. Now, whenever the victim is connected, his latitude and longitude will also be displayed.

Besides, English is not my native language. I got it out of Google translation. Please forgive me if the grammar is not right. Thank you.

### CODE REVIEW

**Comment by Micrafast** [comment]
The change of SocialFishTermux.py is meaningless, you can use the older version

**Comment by usama7628674** [comment]
@Micrafast Can you enhance it further like adding user-agent,city,country,ip so we don't need to rely on `ip.php` and `base.php`

**Comment by Micrafast** [comment]
@usama7628674 ok, i'll try it

**Comment by usama7628674** [comment]
@Micrafast This one is merged submit new PR.

**Comment by Micrafast** [comment]
@usama7628674 yeah i've done it now
[Pull Request](https://github.com/An0nUD4Y/SocialFish/pull/40)

**Pull request merged**
