### PR TITLE
remove ngrok for serveo server

### PR DESCRIPTION
**Pull request by usama7628674**
This PR is follow-up of #74 .Once #74 is merged this will replace ngrok with serveo.

### CODE REVIEW

**Comment by usama7628674** [comment]
@alexmozzhakov Works fine on termux.

**Comment by alexmozzhakov** [comment]
Great. Then you can add removing commit for SocialFishTermux.py into this PR

**Comment by alexmozzhakov** [comment]
@usama7628674 why to master?

**Comment by usama7628674** [comment]
Master is default branch.Once this is merged I'll delete this branch (patch-1)

**Comment by alexmozzhakov** [comment]
@usama7628674 I mean https://github.com/An0nUD4Y/SocialFish/commit/fa96c95e53375b90901ffae148a0bd576a298b04 should be in the PR

**Comment by alexmozzhakov** [comment]
@usama7628674 Agh, stop merging commits, related to this PR, into master 😠

**Comment by usama7628674** [comment]
This PR is about removing ngrok so that only serveo will be used as only one default server.

**Comment by alexmozzhakov** [comment]
@usama7628674 but unless you remove ngrok you can't use regular version from termux.

**Comment by usama7628674** [comment]
Should I proceed with it?

**Comment by alexmozzhakov** [comment]
@usama7628674 do whatever you wan't, I'm just saying that IMO your PRs and commits and inconsistent, you've created PR conflict and right now this code doesn't work on termux

**Comment by usama7628674** [comment]
Yeah I know about conflict but after merging both PR it'll work in termux

**Comment by usama7628674** [comment]
@alexmozzhakov The code now works fine on termux and linux.

**Comment by An0nUD4Y** [comment]
@usama7628674  Please verify if you have tested it a lot... Because for me its not working as it should...? I hope you will test it again.....

**Pull request merged**
